"""empty message

Revision ID: db42fc9f832a
Revises: a2e9bd155d80
Create Date: 2021-02-20 17:51:02.742418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db42fc9f832a'
down_revision = 'a2e9bd155d80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actors', sa.Column('name', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('actors', 'name')
    # ### end Alembic commands ###
